# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Check test before Pull Request
 
on: 
 push:
  branches:    
   - main
   - 'feature/**'
   - develop
 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # github 코드 저장소에 올려둔 코드를 CI 서버로 내려받은 후 특정 브랜치로 전환 -> 현재는 main이므로 상관 없음.
      - uses: actions/checkout@v3 
 
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'
 
      # 파일 실행 권한
      - name: Run the Maven verify phase
        # update-snapshots : cache된 것을 사용하지 않도록 해줌.
        # verify : intergration test. unit test 쓸거면 test쓰라고 하긴 하는데 뭔가 둘 다 할 거 같으면 verify
        # batch-mode : it will for example suppress upload messages to avoid polluting the console log.
        run: mvn --batch-mode --update-snapshots test
